#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Shark.Resource", IsApplication=true)]

namespace Shark
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int androidcolors = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040013
			public const int black = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int black_overlay = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int blue = 2130968580;
			
			// aapt resource value: 0x7f04000e
			public const int customeblue = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int darkblue = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int darkgreen = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int darkorange = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int darkpurple = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int darkred = 2130968589;
			
			// aapt resource value: 0x7f040006
			public const int green = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int lbany = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int lightblue = 2130968577;
			
			// aapt resource value: 0x7f04000f
			public const int lowDarkfont = 2130968591;
			
			// aapt resource value: 0x7f040007
			public const int orange = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int privat_blue = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int purple = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int red = 2130968584;
			
			// aapt resource value: 0x7f040010
			public const int white = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int whiteback = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int whitebackground = 2130968594;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bitbolicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bluebutton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int doberman = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int exit2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hanyiocon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int homehome = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int shark_logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int WhileBackground = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int Activities = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int Careers = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int Contact = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int Exit = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int Home = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int News = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int about = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int textView1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int webView1 = 2131296257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060007
			public const int Activities = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int Careers = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Contact = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int Exit = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int News = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int about = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int home = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int MyCustomTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
