#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("R_Calculatour.Resource", IsApplication=true)]

namespace R_Calculatour
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Controls.Resource.String.library_name = global::R_Calculatour.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int androidcolors = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050010
			public const int black = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int black_overlay = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int blue = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int customeblue = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int darkblue = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int darkgreen = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int darkorange = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int darkpurple = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int darkred = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int green = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int lowDarkfont = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int orange = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int purple = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int red = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int white = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int whiteback = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int whitebackground = 2131034127;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bluebutton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int WhileBackground = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001b
			public const int add = 2131230747;
			
			// aapt resource value: 0x7f080006
			public const int btn1 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int btn2 = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int btn3 = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public const int btn4 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int btn5 = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int btn6 = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int btn7 = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int btn8 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int btn9 = 2131230738;
			
			// aapt resource value: 0x7f080017
			public const int btnClear = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int btn_dot = 2131230742;
			
			// aapt resource value: 0x7f080019
			public const int btn_ysawy = 2131230745;
			
			// aapt resource value: 0x7f080015
			public const int btn_zreo = 2131230741;
			
			// aapt resource value: 0x7f080013
			public const int darb = 2131230739;
			
			// aapt resource value: 0x7f080004
			public const int editText1 = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int gam3 = 2131230729;
			
			// aapt resource value: 0x7f08001a
			public const int home = 2131230746;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int linearLayout2 = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout3 = 2131230730;
			
			// aapt resource value: 0x7f08000f
			public const int linearLayout4 = 2131230735;
			
			// aapt resource value: 0x7f080014
			public const int linearLayout5 = 2131230740;
			
			// aapt resource value: 0x7f080003
			public const int linearLayout6 = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout7 = 2131230721;
			
			// aapt resource value: 0x7f08001c
			public const int more = 2131230748;
			
			// aapt resource value: 0x7f080018
			public const int qsma = 2131230744;
			
			// aapt resource value: 0x7f08000e
			public const int tar7 = 2131230734;
			
			// aapt resource value: 0x7f080002
			public const int wel = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int msg = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
